=head1 NAME

CMDBExplorer - A graphical CMDB explorer using graphviz

=head1 SYNOPSIS

This OTRS package provides a graphical explorer to the OTRS CMDB.

It is based on the excellent work from Dietmar Berg, B<ITSMTrace> 
(version 0.8.1).

B<CMDBExplorer> differs from B<ITSMTrace> by the following characteristics:

  1- The image generated is integrated in the AgentITSMConfigItemZoon screen;
  2- The image initialy shows only first level links. But is interactive, so 
     that the agent can click on a node/CI to further develop the 
     vizualisation of the links;
  3- A lot of CMDBExplorer parameters are configurable via SysConfig settings.

=head1 SYSTEM REQUIREMENTS

B<CMDBExplorer> has been tested on the following platform:

  Ubuntu 12.04.4
  OTRS framework 3.2.8
  ITSM module 3.2.6
  graphviz 2.26.3-10ubuntu1.1
  libgraphviz-perl 2.04-1

Please note that B<CMDBExplorer> will create new, customized,
I<AgentITSMConfigItemZoom.pm> and I<AgentITSMConfigItemZoom.dtl> files. So 
any existing changes on these files might get lost during the installation!

=head1 CONFIGURATION

=head2 CMDBExplorer::GraphOptions###DisplayLinksName

Whether links name should be displayed in the CMDB explorer graph or not

=head2 CMDBExplorer::GraphOptions###RootNodeColor

Fillcolor of the Root node. The root node is the one that's currently displayed
in the AgentITSMConfigItemZoom screen (must be a valid graphviz color).

=head2 CMDBExplorer::GraphOptions###DisplayedNodeColor

Defines the fillcolor of the nodes that have been specificaly selected by the
agent for inclusion in the graph (must be a valid graphviz color).

=head2 CMDBExplorer::GraphOptions###LinkDefaultColor

Default link color (must be a valid graphviz color)

=head2 CMDBExplorer::GraphOptions###LinkDefaultFontColor

Default link font's color when link labels are displayed (must be a valid 
graphviz color).

=head2 CMDBExplorer::GraphOptions###LinkFontSize

Font size for the link labels (if displayed)

=head2 CMDBExplorer::GraphOptions###LinkStyles

Defines the styles (eg: filled, dotted) that will be user for rendering links
in the explorer graph. Values must be valid graphviz edge style (see dot's 
man page).

=head2 CMDBExplorer::GraphOptions###LinkArrows

Defines which arrows must be drawn for links in the explorer graph. Values must 
be valid graphviz edge dir (see dot's man page).

=head2 CMDBExplorer::GraphOptions###NodeDefaultColor

Default node color (must be a valid graphviz color)

=head2 CMDBExplorer::GraphOptions###NodeDefaultFillColor

Default node fillcolor (must be a valid graphviz color)

=head2 CMDBExplorer::GraphOptions###NodeFontSize

Font size for the node labels

=head2 CMDBExplorer::GraphOptions###NodeShapes

Defines the shapes (eg: box, ellipse, none) that will be user for rendering 
nodes in the explorer graph. Values must be valid graphviz node shape (see 
dot's man page).

=head2 CMDBExplorer::GraphOptions::LayoutOptions###dot

Defines rendering options for the 'dot' graphviz layout. Values must be valid graphviz 
options for the selected layout (see dot's man page).

=head2 CMDBExplorer::GraphOptions::LayoutOptions###neato

Defines rendering options for the 'neato' graphviz layout. Values must be valid
graphviz options for the selected layout (see dot's man page).

=head2 CMDBExplorer::GraphOptions::LayoutOptions###twopi

Defines rendering options for the 'twopi' graphviz layout. Values must be valid
graphviz options for the selected layout (see dot's man page).

=head2 CMDBExplorer::GraphOptions::LayoutOptions###circo

Defines rendering options for the 'circo' graphviz layout. Values must be valid
graphviz options for the selected layout (see dot's man page).

=head2 CMDBExplorer::GraphOptions::LayoutOptions###fdp

Defines rendering options for the 'fdp' graphviz layout. Values must be valid
graphviz options for the selected layout (see dot's man page).

=head2 CMDBExplorer::GraphOptions::LayoutOptions###sfdp

Defines rendering options for the 'sfdp' graphviz layout. Values must be valid
graphviz options for the selected layout (see dot's man page).

=head1 PACKAGING

B<CMDBExplorer> may easily be repackaged from its git repository by cloning it on
a system running OTRS and issuing the following command:

C<otrs.PackageManager.pl -a build -p /path/to/OTRSCMDBExplorer.sopm -d module-home-path>

=head1 POSSIBLE FUTURE ENHANCEMENTS

Without committing to anything on this list, the following features seem 
worthwhile to be followed up.

=over 4

=item * Test CMDBExplorer on different platforms

CMDBExplorer has only be tested on the OTRS 3.2.x framework with
ITSMConfigurationManagement version 3.2.6, and should be tested on other 
versions.

The installer will prevent you from installing B<CMDBExplorer> on other versions of
the framework and on versions of the ITSMConfigurationManagement module lower
than 3.2.3. This can be easily overcomed by repackaging it though (see chapter 
I<PACKAGING> here above).

=item * Make CMDBExplorer more flexible with the version of the ITSMConfigurationManagement package needed. 

B<CMDBExplorer> ships with a modified version of the I<AgentITSMConfigItemZoom.pm>
and I<AgentITSMConfigItemZoom.dtl> files taken from ITSMConfigurationManagement
version3.2.6. This makes it difficult to make B<CMDBExplorer> compatible with 
other versions of the ITSMConfigurationManagement module.

A solution might be found by using the <CodeInstall> section of 
the .sopm file.

=item * Allow Trace Options to be selected in the Web UI

The Web UI currently comes with predefined links that set a few options
to reasonable values. This can be adapted through C<SysConfig>, but is 
static from an agent's point of view. It would be useful to have an 
intermediate form page where the agent can individually select what 
to include in the output or not.

=back

=head1 TERMS AND CONDITIONS

 Copyright (C) 2014- Belnet, http://www.belnet.be E<10>
 Copyright (C) 2011-2014 Thales Austria GmbH, http://www.thalesgroup.com/

This software comes with ABSOLUTELY NO WARRANTY and WITHOUT ANY SUPPORT. 

For license information, see the enclosed file COPYING-CMDBExplorer
(GNU AFFERO GENERAL PUBLIC LICENSE, version 3). 
If you did not receive this file, see 
http://www.gnu.org/licenses/agpl-3.0.html.

=head1 AUTHOR 

 cyrille.bollu@belnet.be 
 dietmar.berg@thalesgroup.com

=cut

########################################################################
# PDF Production (atviesu0005):
pod2man CMDBExplorer.pod > CMDBExplorer.man; \
groff -man CMDBExplorer.man > CMDBExplorer.ps; \
gs -dCompatibilityLevel=2 -dNOPAUSE -dBATCH \
 -dAutoRotatePages=/None -sDEVICE=pdfwrite \
 -sOutputFile=CMDBExplorer.pdf CMDBExplorer.ps 
########################################################################
